### CREATE USER : SIGNUP
POST http://localhost:3000/auth/signup
Content-type : application/json

{
    "email": "john@yahoo.fr",
    "password": "test"

}

### GET USER BY ID
GET http://localhost:3000/auth/10