### CREATE REPORT

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Yaris",
    "year": 2020,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 10000
}

### Approve an existing report

PATCH http://localhost:3000/reports/16
Content-Type: application/json

{
    "approved": true
}


### GET AN ESTIMATE FOR EXISTING VEHICLE
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=20000&year=2002
